export enum Pages {
  Home = '/home',
  Courses = '/courses',
  About = '/about',
  Login = '/login',
  SignUp = '/sign-up',
  ForgotPassword = '/forgot-password',
  Contact = '/contact',
  Logout = '/logout',
  StudentDashboard = '/student-dashboard',
  StudentCourses = '/student-courses',
  StudentCourseDetails = '/student-course-details',
  InstructorDashboard = '/instructor-dashboard',
  InstructorCreateCourse = '/instructor-create-course',
  InstructorManageCourse = '/instructor-manage-course',
}
